### ISSUE TITLE
Ted is blocking text in pdf

### ISSUE THREAD

**Issue by lievendf** [PeterJudge-PSC/ooabl_patterns#1]
![afbeelding](https://user-images.githubusercontent.com/8639525/131319171-701812f5-7e66-4146-a5bf-49056b31e340.png)

You can still select/copy/paste the text somewhere else as a workaround, but it's not pretty...

**Comment by PeterJudgeZA** [comment]
The text behind Sad Bear Ted is the same as on slide 37. 

And you get the First Post prize ;)
